openapi: 3.0.2
info:
  title: Sentinel
  description: Home Automation and Monitoring IoT
  contact:
    name: Alexandre Lamberty
    url: alexandrelamberty.com
    email: mail@alexandrelamberty.com
  license:
    name: MIT License
    url: "https://opensource.org/licenses/MIT"
  version: 0.0.1
servers:
  - url: "https://development.api.192.168.1.50"
    description: Development server
  - url: "https://staging.api.192.168.1.50"
    description: Staging server
  - url: "https://api.192.168.1.50"
    description: Production server
paths:
  /info:
    get:
      summary: Retrieve device informations
      tags:
        - device
      responses:
        "200":
          description: Device informations
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Device"
      operationId: getDeviceInfo
      description: Return information about the device
components:
  schemas:
    Device:
      type: object
      title: Device
      description: The informations about this device
      properties:
        name:
          type: string
        info:
          $ref: "#/components/schemas/Info"
        capabilities:
          type: array
          items:
            $ref: "#/components/schemas/Capability"
      required:
        - name
        - capabilities
        - info
    Capability:
      title: Capability
      type: object
      description: ""
      x-examples:
        temperature:
          type: sensor
          kind: temperature
          model: BMP180
          api: temperature
        motion:
          type: sensor
          kind: motion
          model: BMP180
          api: motion
        light:
          type: sensor
          kind: light
          model: BMP180
      properties:
        type:
          type: string
          format: name
          description: The name of the capability
          example: sensor
          enum:
            - sensor
            - controller
        kind:
          type: string
          description: A unqique name
          example: humidity
        model:
          type: string
          example: BMP180
    Info:
      title: DeviceInfo
      type: object
      properties:
        micro_controller:
          type: string
          example: ESP8266 ESP-01
        board:
          type: string
          example: NodeMCU Amica v2 ESP8266 ESP-12F
tags:
  - name: device
    description: Device informations endpoint
