openapi: 3.0.3
info:
  title: OpenAPI
  version: '1.0'
  description: Description
  contact:
    name: Alexandre Lamberty
    url: 'http://alexandrelamberty.com'
    email: mail@alexandrelamberty.com
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'https://development.localhost:8080/v1'
    description: Development server
  - url: 'https://staging.localhost:8080/v1'
    description: Staging server
  - url: 'https://api.localhost:8080/v1'
    description: Production server
paths:
  /api: {}
tags:
  - name: api
    description: An api tag
